"""Fix circles.care_frequency to use server_default

Revision ID: 4ea9922607f3
Revises: 28977c402797
Create Date: 2025-12-05 17:13:59.919459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea9922607f3'
down_revision: Union[str, Sequence[str], None] = '28977c402797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circles', 'care_frequency',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circles', 'care_frequency',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
