"""Initial schema: users, thoughts, circles, intentions, intention_cares, stories

Revision ID: 8f33b4d7c4dd
Revises: 
Create Date: 2025-12-05 15:07:30.305768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f33b4d7c4dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('vibe_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('time_elapsed', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_completed_at'), 'actions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.create_table('circles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('circle_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('care_frequency', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circles_user_id'), 'circles', ['user_id'], unique=False)
    op.create_table('intentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('intention_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='intention_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentions_status'), 'intentions', ['status'], unique=False)
    op.create_index(op.f('ix_intentions_user_id'), 'intentions', ['user_id'], unique=False)
    op.create_table('somethings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('text', 'image', 'video', 'url', name='content_type'), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('is_meaning_user_edited', sa.Boolean(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_somethings_created_at'), 'somethings', ['created_at'], unique=False)
    op.create_index(op.f('ix_somethings_user_id'), 'somethings', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_text', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_completed_at'), 'stories', ['completed_at'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_table('action_intentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('intention_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', 'intention_id', name='uq_action_intention')
    )
    op.create_index(op.f('ix_action_intentions_action_id'), 'action_intentions', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_intentions_intention_id'), 'action_intentions', ['intention_id'], unique=False)
    op.create_table('intention_cares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intention_id', sa.Integer(), nullable=False),
    sa.Column('something_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['something_id'], ['somethings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intention_id', 'something_id', name='uq_intention_something')
    )
    op.create_index(op.f('ix_intention_cares_intention_id'), 'intention_cares', ['intention_id'], unique=False)
    op.create_index(op.f('ix_intention_cares_something_id'), 'intention_cares', ['something_id'], unique=False)
    op.create_table('something_circles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('something_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('is_user_assigned', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['something_id'], ['somethings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('something_id', 'circle_id', name='uq_something_circle')
    )
    op.create_index(op.f('ix_something_circles_circle_id'), 'something_circles', ['circle_id'], unique=False)
    op.create_index(op.f('ix_something_circles_something_id'), 'something_circles', ['something_id'], unique=False)
    op.create_table('story_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'action_id', name='uq_story_action')
    )
    op.create_index(op.f('ix_story_actions_action_id'), 'story_actions', ['action_id'], unique=False)
    op.create_index(op.f('ix_story_actions_story_id'), 'story_actions', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_actions_story_id'), table_name='story_actions')
    op.drop_index(op.f('ix_story_actions_action_id'), table_name='story_actions')
    op.drop_table('story_actions')
    op.drop_index(op.f('ix_something_circles_something_id'), table_name='something_circles')
    op.drop_index(op.f('ix_something_circles_circle_id'), table_name='something_circles')
    op.drop_table('something_circles')
    op.drop_index(op.f('ix_intention_cares_something_id'), table_name='intention_cares')
    op.drop_index(op.f('ix_intention_cares_intention_id'), table_name='intention_cares')
    op.drop_table('intention_cares')
    op.drop_index(op.f('ix_action_intentions_intention_id'), table_name='action_intentions')
    op.drop_index(op.f('ix_action_intentions_action_id'), table_name='action_intentions')
    op.drop_table('action_intentions')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_completed_at'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_somethings_user_id'), table_name='somethings')
    op.drop_index(op.f('ix_somethings_created_at'), table_name='somethings')
    op.drop_table('somethings')
    op.drop_index(op.f('ix_intentions_user_id'), table_name='intentions')
    op.drop_index(op.f('ix_intentions_status'), table_name='intentions')
    op.drop_table('intentions')
    op.drop_index(op.f('ix_circles_user_id'), table_name='circles')
    op.drop_table('circles')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_completed_at'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
